# Generated by Django 4.1.9 on 2023-06-12 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_nom_remove_customuser_prenoms_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='tel',
            new_name='numero',
        ),
    ]
