# Generated by Django 4.1.9 on 2023-06-12 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_tel_customuser_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='numero',
            new_name='tel',
        ),
    ]
